spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false          # 부팅 로그에 계속 뜨던 경고도 정리

  #MySQL 세션 저장소 설정
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always # SPRING_SESSION 테이블 자동 생성
    timeout: 7d # 서버 측 세션 7일 유지

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        max-age: 7d # 프론트엔드 쿠키 7일 유지
        same-site: lax
        secure: true      # HTTPS 환경에서만 동작

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ap-northeast-2
    s3:
      bucket: piccup-bestpick-6th

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  otlp:
    metrics:
      export:
        url: ${GRAFANA_OTLP_URL:http://localhost:4318/v1/metrics} # 로컬에서 사용하려면 디폴트 빼고 환경변수 집어넣기
        headers:
          Authorization: Basic ${GRAFANA_OTLP_AUTH:}
        step: 15s